### ISSUE TITLE
Proposal to talk on 13 Oct. Use case of data visualization  

### ISSUE THREAD

**Issue by VarshitAgarwal** [PyJaipur/Talks#3]
I have made a project  on Extraction of text from an  Image using Deep Learning Framework ( keras) and CNN algorithm where i'll show a real time data visualization  of dataset using python Module.

**Comment by Shivank98** [comment]
We are confirming your talk under lightning talk in the event.
you will be allocated 10 minutes.
It will be great to have you with us :)
